version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: jenkins_docker
    build:
      context: images/jenkins_docker
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins-data:/var/jenkins_home
    restart: always
  jenkins_slave:
    image: jenkinsci/jnlp-slave
    container_name: jenkins_slave_1
    command: -url http://localhost:8080 9342fb2b08caeb4e6643afa29609e346a24a08331ab0f38cc98733de0d2cf284 jnlp-docker-slave
    restart: always
