version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: jenkins_docker
    build:
      context: images/jenkins_docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
    restart: always
  jenkins_slave:
    image: lsegal/jnlp-docker-agent
    container_name: jenkins_slave_1
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/home/workspace/docker-pipe
      - /tmp:/home/workspace/docker-pipe@tmp
      # Make sure to use your Docker ip instead. Get it by looking up ifconfig info
    command: -url http://172.17.0.1:8080 2cc52fb4c7ffac63ea504f7093b1cbc2801eb3d596b55b1d2416fbbcc4afc0b5 node
    restart: always
